### ISSUE TITLE
Character Name Party Alignment

### ISSUE THREAD

**Issue by PhantomandGhost** [Illidanz/VampireTranslation#5]
Character names aren’t centred for the ‘Attending a Party’ mini-game - !FILE:CharacterNames (using >> makes no difference.)

Can be viewed from the title screen > mini game > パーティへおいで (night) if the [game clear save](https://github.com/Illidanz/VampireTranslation/files/6880608/game_clear_save.zip) is used

**Comment by Illidanz** [comment]
Should be fixed in 1.0.4, but there's no room for the last name (Yuki Cross). Needs some improvement.

**Comment by PhantomandGhost** [comment]
Fixed in v1.0.5, although there's an issue with some other minigames which repeat instructions from the bin_input e.g. 'Item Inspection'. Yuki's name is just showing as "Yuki Cro". The one's that are just the 'pick a character' lines from the dat_input work fine. (I think this is an issue which was present in the previous version, I just didn't notice it before.)

They use the split '黒主=Yuki, 優姫=Cross lines from the bin_input, for... whatever reason. I think the limit might be set by the Japanese line, as I can get a max of 8 English letters in.
